# Generated by Django 3.1.1 on 2021-03-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_feedback_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
