# Generated by Django 3.1.1 on 2021-02-08 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and  entered in the format: '98XXXXXXXX'.", regex='^\\+?1?\\d{10}$')])),
                ('number_of_room', models.IntegerField(null=True)),
            ],
        ),
    ]
