# Generated by Django 3.1.1 on 2021-02-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='User',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
