# Generated by Django 3.1.1 on 2021-03-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_hotelinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='number_of_room',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
